# Site settings
title: Foong Min Wong


baseurl: ""
url: "http://localhost:4000"

# Social
facebook: foongminwong
github:  foongminwong
twitter: foongminwong1
linkedin: foongminwong
email: foongmin.wong@hotmail.com

picture: assets/images/profile.png

authors:
    foongminwong:
        name: Foong Min Wong
        picture: assets/images/profile.png


width: normal

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
