# Site settings
title: Foong Min Wong
email: foongmin.wong@hotmail.com

baseurl: ""
url: "http://localhost:4000"
twitter_username: foongminwong1
github_username:  foongminwong

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
